### ISSUE TITLE
Wrong date for reply

### ISSUE THREAD

**Issue by C0D3-M4513R** [ngi-nix/summer-of-nix#21]
In the file:
 https://github.com/ngi-nix/summer-of-nix/blob/master/participants.md
There is the line:
> You will get a reply with the result by 2023-05-13

Juding by the discord post: https://discourse.nixos.org/t/summer-of-nix-2024-call-for-participants/43249?u=nobbz
That date is meant to be in the future, rather than in the past.

Similarly in this file:
 https://github.com/ngi-nix/summer-of-nix/blob/master/facilitators.md
> You will get a reply with the result by 2023-04-01

**Comment by fricklerhandwerk** [comment]
Thanks, fixed in https://github.com/ngi-nix/summer-of-nix/commit/3684fddcc7379204d213256a480c9c12f0e45a28

**Comment by C0D3-M4513R** [comment]
Still an issue in facilitators.md
