### ISSUE TITLE
Confusion with Wording in README

### ISSUE THREAD

**Issue by GhoulBoii** [ngi-nix/summer-of-nix#23]
> Be a natural person of legal age

Could I get more clarification on what a natural person of legal age implies?

**Comment by fricklerhandwerk** [comment]
Hi @GhoulBoii, thanks for asking.

[Natural person](https://en.wikipedia.org/wiki/Natural_person) - a human being as opposed to an organisation like a company, or, which may or may not age well, an artificial autonomous agent. 

[Age of majority](https://en.wikipedia.org/wiki/Age_of_majority) - you have to be X years old to do certain things, such as signing contracts, which depends on the country.

Feel free to re-open if you still have questions. :)
